## Checkout our full reference doc at https://neu-ro.gitbook.io/neuro-flow/reference/live-workflow-syntax

id:  {{ cookiecutter.project_slug }}
# Could be referenced as $[[ project.id ]] or $[[ flow.project_id ]] contexts.
# Default value - folder name, where .neuro folder is located

# owner: {ownername}
# Optional platform user, who owns the project, referenced via $[[ project.owner ]]

# role: {rolename}
# Optional platform role, which might be used to share the project
# with other platform users via `neuro acl grant <role> <user>`
