version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "15:00"
      timezone: Europe/Kyiv
    allow:
      - dependency-type: "all"
    reviewers:
      - neuro-inc/mlops
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      time: "15:00"
      timezone: Europe/Kyiv
    reviewers:
      - neuro-inc/mlops
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "15:00"
      timezone: Europe/Kyiv
    reviewers:
      - neuro-inc/mlops
