[tool.towncrier]
    directory = "CHANGELOG.D"
    filename = "CHANGELOG.md"
    template = "CHANGELOG.D/towncrier_template.md"
    issue_format = "[#{issue}](https://github.com/neuro-inc/cookiecutter-neuro-project/issues/{issue})"
    start_string = "[comment]: # (towncrier release notes start)\n"

    [[tool.towncrier.type]]
        directory = "feature"
        name = "Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bugfixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "doc"
        name = "Improved Documentation"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "removal"
        name = "Deprecations and Removals"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "misc"
        name = "Misc"
        showcontent = false
