# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test_dev:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/neuromation-template

    steps:
      - checkout

      - restore_cache:
          keys:
            - &pip_packages_cache_key v1-dependencies-3.7.3-{{ checksum "requirements-dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            make init

      - save_cache:
          paths:
            - ./venv
          key: *pip_packages_cache_key

      - run:
          name: run linter
          command: |
            . venv/bin/activate
            make lint

      - run:
          name: run unit tests
          command: |
            . venv/bin/activate
            make test_unit

      - run:
          name: run e2e tests
          command: |
            . venv/bin/activate
            make test_e2e_dev

      - run:
          name: clean up
          command: |
            . venv/bin/activate
            python cleanup_jobs.py
            rm -f ~/.nmrc
          when: always

      - store_artifacts:
          path: ./submitted_jobs.txt
          destination: submitted-jobs

  test_staging:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/neuromation-template
    steps:
      - checkout

      - restore_cache:
          keys:
            - &pip_packages_cache_key v1-dependencies-3.7.3-{{ checksum "requirements-dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            make init

      - save_cache:
          paths:
            - ./venv
          key: *pip_packages_cache_key

      - run:
          name: run linter
          command: |
            . venv/bin/activate
            make lint

      - run:
          name: run unit tests
          command: |
            . venv/bin/activate
            make test_unit

      - run:
          name: run e2e tests
          command: |
            . venv/bin/activate
            make test_e2e_staging

      - run:
          name: clean up
          command: |
            . venv/bin/activate
            python cleanup_jobs.py
            rm -f ~/.nmrc
          when: always

      - store_artifacts:
          path: ./submitted_jobs.txt
          destination: submitted-jobs



workflows:
  version: 2

  main:
    jobs:
      - test_dev

      - test_staging:
          filters:
            branches:
#              only: master
              only: /.*/
