version: 2.1

defaults: &defaults
  machine:
    image: circleci/classic:201808-01
    docker_layer_caching: true
  working_directory: ~/platform-monitoring

jobs:
  test:
    <<: *defaults

    working_directory: ~/neuromation-template

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements-dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pyenv install --debug 3.6.7
            pyenv local 3.6.7-debug
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            make init

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements-dev.txt" }}

      - run:
          name: run linter
          command: |
            . venv/bin/activate
            make lint

      - run:
          name: run unit tests
          command: |
            . venv/bin/activate
            make test_unit

      - run:
          name: run e2e tests
          command: |
            . venv/bin/activate
            make test_e2e
      #
      # - store_artifacts:
      #     path: test-reports
      #     destination: test-reports

      - run:
          name: clean up running jobs
          command: |
            . venv/bin/activate
            python tests/e2e/cleanup_jobs.py
          when: always

workflows:
  version: 2

  main:
    jobs:
      - test
