version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  allow:
    - dependency-type: "all"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
