stages:
- stage: unit
  displayName: "Unit"
  jobs:
  - job:
    displayName: " "
    strategy:
      matrix:
        Py37-Linux:
          python.version: '3.7'
          image: 'ubuntu-latest'

    pool:
      vmImage: $[ variables['image'] ]

    timeoutInMinutes: 30

    steps:
    - checkout: self
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: "Use Python $(python.version)"

    - script: |
        python -m pip install -U pip
      displayName: 'Install pre-requirements'
    - script: |
        make setup
      displayName: 'Install dependencies'
    - script: |
        make test_unit
      displayName: 'Run unittests'
    - script: |
        make lint
      displayName: 'Run linters'

