name: CI

on:
  push:
    branches: [ master, release ]
  pull_request:
    branches: [ master ]
  pull_request_target:
    branches: [master]
  release:
    types: [ published ]


jobs:

  test:
    if: |
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')
    name: Run tests
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        os: [ubuntu, macos, windows]
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    env:
      PYTHONIOENCODING: utf-8
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python and its deps
        uses: actions/cache@v2.1.7
        with:
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('requirements/*.txt') }}
          path: ${{ env.pythonLocation }}

      - name: Install GNU libraries for MacOS
        if: matrix.os == 'macos'
        shell: bash
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install findutils
          echo PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH" >> $GITHUB_ENV

      - name: Install python dependencies
        run: |
          make setup

      - name: Configure environment
        run: |
          neuro config login-with-token ${{ secrets.NEURO_TOKEN }} ${{ secrets.NEURO_STAGING_URL }}
          neuro --color=no config show

      - name: Lint
        run: |
          make lint

      - name: Run tests
        run: |
          make test
