name: Update mlflow tags
on:
  schedule:
  - cron: 0 0 * * *
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install pygithub
    - name: Run update actions script
      run: python update_actions.py --input “.neuro/*.y*ml"
    - id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.BOT_APP_ID }}
        private_key: ${{ secrets.BOT_PRIVATE_KEY }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.10.1
      with:
        token: ${{ steps.generate_token.outputs.token }}
        branch: update/image-tags
        title: Auto-update image tags
        commit-message: Auto-update image tags
        body: |
          Update versions of image in helm values
          configs to latest version
