name: Update neuro-flow action tags
on:
  schedule:
  - cron: 0 0 * * *
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: make setup
    - id: run_updater
      name: Run update actions script
      run: python \{\{cookiecutter.project_dir\}\}/update_actions.py ".neuro/*.y*ml"
    - id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.BOT_APP_ID }}
        private_key: ${{ secrets.BOT_PRIVATE_KEY }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ steps.generate_token.outputs.token }}
        branch: update/actions-tags
        title: Auto-update actions tags
        commit-message: Auto-update neuro-flow actions tags
        body: |
          Updated neuro-flow action version tags in the following
          files: ${{ steps.run_updater.outputs.updated_files }}
